import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../../styles/blog.module.css";

const Blog = () => {
  const data = [1, 2, 3, 4, 5];
  const router = useRouter();
  return (
    <div style={{ padding: "20px" }}>
       <Head>
        <title>Blog-详情页</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2>
        技术博客
      </h2>
      {data.map((item) => (
        <p
          key={item}
          onClick={() => {
            router.push(`/blog/${item}`);
          }}
          className={styles.title}
        >
          博客{item}
        </p>
      ))}
    </div>
  );
};
export default Blog;
